server:
  port: 9087
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.238.101:3306/test1?useUnicode=true&characterEncoding=utf-8
  boot:
    admin:
      client:
        url: http://localhost:9980
        username: joe
        password: 123456
  application:
    name: hiynn-spring-mybatis
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
info:
  name: hiynn-spring-mybatis
  version: 1.0.0
  email: a864511019@163.com

debug: true