server:
  port: 9978
spring:
  redis:
    database: 15
    port: 6339
    password: 123456
    host: 10.0.92.127
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  datasource:
    other:
      username: root
      password: 123456
      jdbcUrl: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          scheduler:
            instanceName: HiynnScheduler
            instanceId: AUTO
            idleWaitTime: 5000
            threadName: HIYNN
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: HIYNN
            misfireThreshold: 5000 #导致重新启动执行错过的时间设置10s以下
            isClustered: true
            useProperties: true
          datasource:
            username: root
            password: 123456
            jdbcUrl: jdbc:mysql://localhost:3306/hiynn_quartz?useUnicode=true&characterEncoding=utf-8
            driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: test
logging:
  config: classpath:logback-spring.xml
task:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10
file:
  base:
    import-path: F:\activemq-ftp\import\
    export-path: F:\activemq-ftp\export\
