spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.238.101:3306/hiynn_quartz?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    jdbc:
#      initialize-schema: EMBEDDED
      schema: classpath:quartz/tables_mysql.sql
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          scheduler:
            instanceName: HiynnScheduler
            instanceId: AUTO
            idleWaitTime: 5000
            threadName: HIYNN
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: HIYNN
            misfireThreshold: 60000
            isClustered: true
            useProperties: true
