server:
  port: 8083
spring:
  thymeleaf:
#    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.238.101:3306/test3?useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
hiynn:
  security:
    browser:
      login-page: /demoLogin #自定义配置登录页

people:
  woman:
    name: nv
  man:
    name: nan
