server:
  port: 9981
  servlet:
    context-path: /client
spring:
  boot:
    admin:
      client:
        url: http://localhost:9980
  application:
    name: hiynn-admin-client
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'