server:
  port: 8769
spring:
  application:
    name: hiynn-spring-mybatis-plus
  datasource:
    url: jdbc:mysql://10.0.91.88:3306/datacenter_dataservice?useUnicode=true&useSSL=false&characterEncoding=utf8
    password: 1qazCDE#
    username: fangyuan
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level.com.hiynn.spring.mybatis.plus.mapper: debug