upload:
  file:
    path: D:\var\log\
server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:9980
        username: joe
        password: 123456
  application:
    name: hiynn-file-upload
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
info:
  name: hiynn-file-upload
  version: 1.0.0
  email: a864511019@163.com
